export const PERMISSOES = {

  DASHBOARD: {
    VISUALIZAR: 'DASHBOARD_VISUALIZAR',
  },

  CLIENTE: {
    VISUALIZAR: 'CLIENTE_VISUALIZAR',
    CRIAR: 'CLIENTE_CRIAR',
    EDITAR: 'CLIENTE_EDITAR',
    DESATIVAR: 'CLIENTE_DESATIVAR',
  },

  APARELHO: {
    VISUALIZAR: 'APARELHO_VISUALIZAR',
    CRIAR: 'APARELHO_CRIAR',
    EDITAR: 'APARELHO_EDITAR',
  },

  ORDEM_SERVICO: {
    VISUALIZAR: 'OS_VISUALIZAR',
    CRIAR: 'OS_CRIAR',
    EDITAR: 'OS_EDITAR',
    FINALIZAR: 'OS_FINALIZAR',
    ENTREGAR: 'OS_ENTREGAR',
    CANCELAR: 'OS_CANCELAR',
    IMPRIMIR: 'OS_IMPRIMIR',
  },

  ORCAMENTO: {
    VISUALIZAR: 'ORCAMENTO_VISUALIZAR',
    CRIAR: 'ORCAMENTO_CRIAR',
    EDITAR: 'ORCAMENTO_EDITAR',
    ENVIAR: 'ORCAMENTO_ENVIAR',
    APROVAR: 'ORCAMENTO_APROVAR',
    REPROVAR: 'ORCAMENTO_REPROVAR',
  },

  PAGAMENTO: {
    VISUALIZAR: 'PAGAMENTO_VISUALIZAR',
    REGISTRAR: 'PAGAMENTO_REGISTRAR',
    ESTORNAR: 'PAGAMENTO_ESTORNAR',
  },

  RELATORIO: {
    TECNICO_VISUALIZAR:
      'RELATORIO_TECNICO_VISUALIZAR',
  },

  USUARIO: {
    VISUALIZAR: 'USUARIO_VISUALIZAR',
    CRIAR: 'USUARIO_CRIAR',
    EDITAR: 'USUARIO_EDITAR',
    DESATIVAR: 'USUARIO_DESATIVAR',
    PERMISSAO_GERENCIAR:
      'USUARIO_PERMISSAO_GERENCIAR',
  },

} as const;