server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;
    default_type text/html;

    charset utf-8;

    location / {
        try_files $uri $uri/ =404;
    }
}