name: Deploy Kubernetes

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Versão da imagem'
        required: true
        default: 'latest'

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: self-hosted

    env:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Definir variáveis
        run: |
          APP_NAME=$(basename $GITHUB_REPOSITORY)
          IMAGE=ghcr.io/${{ github.repository }}:${{ github.event.inputs.version }}

          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t $IMAGE .

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push $IMAGE

      - name: Deploy
        run: |
          echo "Deployando $APP_NAME"

          if kubectl get deployment ${APP_NAME}-app -n prod > /dev/null 2>&1; then
            echo "Atualizando deployment"
            kubectl set image deployment/${APP_NAME}-app app=$IMAGE -n prod
          else
            echo "Criando deployment"

            kubectl create deployment ${APP_NAME}-app --image=$IMAGE -n prod
            kubectl expose deployment ${APP_NAME}-app --port=80 --target-port=80 -n prod

            echo "apiVersion: networking.k8s.io/v1" > ingress.yaml
            echo "kind: Ingress" >> ingress.yaml
            echo "metadata:" >> ingress.yaml
            echo "  name: ${APP_NAME}-app" >> ingress.yaml
            echo "  namespace: prod" >> ingress.yaml
            echo "spec:" >> ingress.yaml
            echo "  rules:" >> ingress.yaml
            echo "    - host: ${APP_NAME}.cluster.stringtecnologiadf.org" >> ingress.yaml
            echo "      http:" >> ingress.yaml
            echo "        paths:" >> ingress.yaml
            echo "          - path: /" >> ingress.yaml
            echo "            pathType: Prefix" >> ingress.yaml
            echo "            backend:" >> ingress.yaml
            echo "              service:" >> ingress.yaml
            echo "                name: ${APP_NAME}-app" >> ingress.yaml
            echo "                port:" >> ingress.yaml
            echo "                  number: 80" >> ingress.yaml

            kubectl apply -f ingress.yaml
          fi

          kubectl rollout status deployment/${APP_NAME}-app -n prod