name: Deploy Kubernetes

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Versão'
        required: true
        default: 'latest'

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: self-hosted

    env:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    steps:
      # 🔹 checkout app
      - name: Checkout app
        uses: actions/checkout@v4

      # 🔹 variáveis
      - name: Definir variáveis
        run: |
          APP_NAME=$(basename $GITHUB_REPOSITORY)
          IMAGE=ghcr.io/${{ github.repository }}:${{ github.event.inputs.version }}

          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # 🔹 build imagem
      - name: Build
        run: docker build -t $IMAGE .

      # 🔐 login GHCR
      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 📦 push
      - name: Push
        run: docker push $IMAGE

      # 🔥 checkout infra
      - name: Checkout infra
        run: |
          rm -rf app-cluster
          git clone https://github.com/samuelmelo98/app-cluster.git

      # 🚀 deploy (CORRIGIDO)
      - name: Deploy declarativo
        run: |
          set -e

          APP_NAME=$(basename $GITHUB_REPOSITORY)

          cd app-cluster/k8s/overlays/prod/$APP_NAME

          echo "🚀 Deployando: $APP_NAME"
          echo "📦 Imagem: $IMAGE"

          # atualiza imagem
          kustomize edit set image IMAGE_PLACEHOLDER=$IMAGE

          # tenta aplicar (pode falhar na primeira vez por selector imutável)
          kubectl apply -k . -n prod || true

          # recria deployment se necessário
          kubectl delete deployment ${APP_NAME}-app -n prod || true

          # aplica novamente (estado final correto)
          kubectl apply -k . -n prod

          # aguarda rollout
          kubectl rollout status deployment/${APP_NAME}-app -n prod